# Generated by Django 4.2.4 on 2023-08-23 01:50

from django.db import migrations, models
import uuid


def generate_unique_uuids(apps, schema_editor):
    PhotoModel = apps.get_model("photos", "Photo")
    for photo in PhotoModel.objects.all():
        while True:
            new_uuid = uuid.uuid4()
            print(new_uuid)
            if not PhotoModel.objects.filter(photo_uuid=new_uuid).exists():
                break
        photo.photo_uuid = new_uuid
        photo.item_uuid = photo.item_id
        photo.save()


class Migration(migrations.Migration):
    dependencies = [
        ("photos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="item_uuid",
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="photo",
            name="photo_uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.RunPython(generate_unique_uuids),
    ]
