# Generated by Django 4.2.4 on 2023-08-23 01:50

from django.db import migrations, models
import uuid


def generate_unique_uuids(apps, schema_editor):
    WishlistModel = apps.get_model("wishlists", "Wishlist")
    for wishlist in WishlistModel.objects.all():
        while True:
            new_uuid = uuid.uuid4()
            if not WishlistModel.objects.filter(wishlist_uuid=new_uuid).exists():
                break
        wishlist.wishlist_uuid = new_uuid
        wishlist.save()


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0013_auctionitem_fixedpriceitem"),
        ("wishlists", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="wishlist",
            name="wishlist_uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="wishlist",
            name="items",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="wishlists", to="items.item"
            ),
        ),
        migrations.RunPython(generate_unique_uuids),
    ]
