# Generated by Django 4.2.4 on 2023-08-23 01:50

from django.db import migrations, models
import uuid


def migrate_items_to_fixed_price_items(apps, schema_editor):
    Item = apps.get_model("items", "Item")
    FixedPriceItem = apps.get_model("items", "FixedPriceItem")

    for item in Item.objects.all():
        fixed_price_item = FixedPriceItem(
            # item_uuid=item.pk,
            user_id=item.user_id,
            buy_user_id=item.buy_user_id,
            item_name=item.item_name,
            is_sold=item.is_sold,
            is_deleted=item.is_deleted,
            used_years=item.used_years,
            manufactured_date=item.manufactured_date,
            description=item.description,
            category=item.category,
            location=item.location,
            price=item.price,
            is_negotiable=item.is_negotiable,
            temp_user_id=item.user_id,
            temp_item_id=item.id,
        )
        fixed_price_item.save()


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0012_alter_item_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuctionItem",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "item_uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("user_id", models.TextField(default="")),
                ("buy_user_id", models.TextField(blank=True, default="", null=True)),
                ("item_name", models.CharField(default="", max_length=20)),
                ("is_sold", models.BooleanField(default=False)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "used_years",
                    models.CharField(
                        choices=[
                            ("1년 이하", "1년 이하"),
                            ("1년~2년", "1년~2년"),
                            ("2년~3년", "2년~3년"),
                            ("3년~4년", "3년~4년"),
                            ("4년~5년", "4년~5년"),
                            ("5년 이상", "5년 이상"),
                        ],
                        max_length=20,
                    ),
                ),
                ("manufactured_date", models.DateField(blank=True, null=True)),
                ("is_manufactured", models.BooleanField(default=True)),
                ("description", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("가구", "가구"),
                            ("커피머신", "커피머신"),
                            ("제빙기", "제빙기"),
                            ("냉장고/냉동고", "냉장고/냉동고"),
                            ("세척기", "세척기"),
                            ("쇼케이스", "쇼케이스"),
                            ("싱크대/작업대", "싱크대/작업대"),
                            ("가스레인지/인덕션", "가스레인지/인덕션"),
                            ("포장기계", "포장기계"),
                            ("에어컨", "에어컨"),
                            ("기타", "기타"),
                        ],
                        max_length=25,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        choices=[
                            ("강남구", "강남구"),
                            ("강동구", "강동구"),
                            ("강북구", "강북구"),
                            ("강서구", "강서구"),
                            ("관악구", "관악구"),
                            ("광진구", "광진구"),
                            ("구로구", "구로구"),
                            ("금천구", "금천구"),
                            ("노원구", "노원구"),
                            ("도봉구", "도봉구"),
                            ("동대문구", "동대문구"),
                            ("동작구", "동작구"),
                            ("마포구", "마포구"),
                            ("서대문구", "서대문구"),
                            ("서초구", "서초구"),
                            ("성동구", "성동구"),
                            ("성북구", "성북구"),
                            ("송파구", "송파구"),
                            ("양천구", "양천구"),
                            ("영등포구", "영등포구"),
                            ("용산구", "용산구"),
                            ("은평구", "은평구"),
                            ("종로구", "종로구"),
                            ("중구", "중구"),
                            ("중량구", "중량구"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("temp_item_id", models.TextField(default="")),
                ("temp_user_id", models.TextField(default="")),
                ("deadline", models.DateTimeField()),
                ("lowest_price", models.PositiveIntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FixedPriceItem",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "item_uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("user_id", models.TextField(default="")),
                ("buy_user_id", models.TextField(blank=True, default="", null=True)),
                ("item_name", models.CharField(default="", max_length=20)),
                ("is_sold", models.BooleanField(default=False)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "used_years",
                    models.CharField(
                        choices=[
                            ("1년 이하", "1년 이하"),
                            ("1년~2년", "1년~2년"),
                            ("2년~3년", "2년~3년"),
                            ("3년~4년", "3년~4년"),
                            ("4년~5년", "4년~5년"),
                            ("5년 이상", "5년 이상"),
                        ],
                        max_length=20,
                    ),
                ),
                ("manufactured_date", models.DateField(blank=True, null=True)),
                ("is_manufactured", models.BooleanField(default=True)),
                ("description", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("가구", "가구"),
                            ("커피머신", "커피머신"),
                            ("제빙기", "제빙기"),
                            ("냉장고/냉동고", "냉장고/냉동고"),
                            ("세척기", "세척기"),
                            ("쇼케이스", "쇼케이스"),
                            ("싱크대/작업대", "싱크대/작업대"),
                            ("가스레인지/인덕션", "가스레인지/인덕션"),
                            ("포장기계", "포장기계"),
                            ("에어컨", "에어컨"),
                            ("기타", "기타"),
                        ],
                        max_length=25,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        choices=[
                            ("강남구", "강남구"),
                            ("강동구", "강동구"),
                            ("강북구", "강북구"),
                            ("강서구", "강서구"),
                            ("관악구", "관악구"),
                            ("광진구", "광진구"),
                            ("구로구", "구로구"),
                            ("금천구", "금천구"),
                            ("노원구", "노원구"),
                            ("도봉구", "도봉구"),
                            ("동대문구", "동대문구"),
                            ("동작구", "동작구"),
                            ("마포구", "마포구"),
                            ("서대문구", "서대문구"),
                            ("서초구", "서초구"),
                            ("성동구", "성동구"),
                            ("성북구", "성북구"),
                            ("송파구", "송파구"),
                            ("양천구", "양천구"),
                            ("영등포구", "영등포구"),
                            ("용산구", "용산구"),
                            ("은평구", "은평구"),
                            ("종로구", "종로구"),
                            ("중구", "중구"),
                            ("중량구", "중량구"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("temp_item_id", models.TextField(default="")),
                ("temp_user_id", models.TextField(default="")),
                ("price", models.PositiveIntegerField()),
                ("is_negotiable", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RunPython(migrate_items_to_fixed_price_items),
    ]
