# Generated by Django 4.2.1 on 2023-05-18 10:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("username", models.CharField(max_length=20)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("name", models.CharField(default="", max_length=20)),
                ("phone_number", models.IntegerField()),
                (
                    "is_business_license_certificated",
                    models.BooleanField(default=False),
                ),
                ("license_number", models.IntegerField()),
                ("license_name", models.CharField(max_length=20)),
                ("license_date", models.DateField()),
                ("is_local_certificated", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
