# Generated by Django 4.2.5 on 2023-09-14 01:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0002_remove_user_is_business_license_certificated_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "user_uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("chat_notification_allowed", models.BooleanField(default=True)),
                ("marketing_notification_allowed", models.BooleanField(default=True)),
                ("is_certificated", models.BooleanField(default=False)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("fcm_token", models.TextField(blank=True, null=True)),
                ("nick_name", models.CharField(max_length=10, unique=True)),
                ("name", models.CharField(max_length=13)),
                ("birth_date", models.DateField()),
                ("sector", models.CharField(max_length=13)),
                ("phone_number", models.CharField(max_length=60, unique=True)),
                ("profile_image_url", models.URLField(blank=True, null=True)),
                (
                    "user_type",
                    models.CharField(
                        choices=[
                            ("kakao", "Kakao Login"),
                            ("apple", "Apple Login"),
                            ("local", "Local Login"),
                        ],
                        default="local",
                        max_length=10,
                    ),
                ),
                ("kakao_id", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        related_name="customuser_set",
                        related_query_name="customuser",
                        to="auth.group",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="customuser_set",
                        related_query_name="customuser",
                        to="auth.permission",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
