# Generated by Django 4.2.5 on 2023-09-14 05:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_customuser_delete_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="temp_user_id",
            field=models.TextField(default=""),
        ),
    ]
