# Generated by Django 4.2.1 on 2023-08-04 07:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_customuser_delete_usermodel"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="password",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="username",
        ),
    ]
