# Generated by Django 4.2.1 on 2023-08-04 07:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_remove_customuser_password_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="birth_date",
            field=models.DateField(),
        ),
    ]
