# Generated by Django 4.2.5 on 2023-09-21 00:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_remove_customuser_temp_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="blocked_users",
            field=models.ManyToManyField(blank=True, to="users.customuser"),
        ),
    ]
