# Generated by Django 4.2.6 on 2023-10-25 02:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_customuser_blocked_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="temp_user_id",
            field=models.TextField(default=""),
        ),
    ]
