# Generated by Django 4.2.1 on 2023-08-08 00:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_rename_nick_name_customuser_nickname_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
