# Generated by Django 4.2.1 on 2023-08-08 01:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_rename_nick_name_customuser_nickname_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="nick_name",
        ),
        migrations.AddField(
            model_name="customuser",
            name="nickname",
            field=models.CharField(default="temp", max_length=10),
            preserve_default=False,
        ),
    ]
