# Generated by Django 4.2.5 on 2023-10-30 04:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_customuser_is_deleted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
