# Generated by Django 4.2.1 on 2023-08-08 01:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_remove_customuser_nick_name_customuser_nickname"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser",
            managers=[],
        ),
        migrations.RenameField(
            model_name="customuser",
            old_name="nickname",
            new_name="nick_name",
        ),
    ]
