# Generated by Django 4.2.5 on 2023-11-28 06:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_alter_customuser_birth_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="gender",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
