# Generated by Django 4.2.1 on 2023-08-08 04:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0011_alter_customuser_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="user_id",
            new_name="user_uuid",
        ),
        migrations.AddField(
            model_name="customuser",
            name="user",
            field=models.OneToOneField(
                default="123",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
