# Generated by Django 4.2.1 on 2023-08-10 06:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0013_alter_customuser_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="nick_name",
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
