# Generated by Django 4.2.1 on 2023-08-17 02:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0015_alter_customuser_options_alter_customuser_managers_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="user",
        ),
    ]
