# Generated by Django 4.2.1 on 2023-08-17 02:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0016_remove_customuser_user"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser",
            managers=[],
        ),
    ]
