# Generated by Django 4.2.1 on 2023-07-28 07:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stats", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="searchstats",
            old_name="most_searched_keyword",
            new_name="searched_keyword",
        ),
    ]
