# Generated by Django 4.2.1 on 2023-07-28 06:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stats", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SearchStatsDaily",
            new_name="SearchStats",
        ),
    ]
