# Generated by Django 4.2.1 on 2023-07-02 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0012_alter_item_dday_date_alter_item_manufactured_date_and_more"),
        ("photos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="item",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="photos",
                to="items.item",
            ),
        ),
    ]
