# Generated by Django 4.2.4 on 2023-09-13 08:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("photos", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="photo",
            name="item_uuid",
        ),
        migrations.AddField(
            model_name="photo",
            name="is_thumbnail",
            field=models.BooleanField(default=False),
        ),
    ]
