# Generated by Django 4.2.4 on 2023-08-24 03:06

from django.db import migrations
from django.contrib.contenttypes.models import ContentType


def migrate_photo_data(apps, schema_editor):
    TempPhoto = apps.get_model("photos", "TempPhoto")
    Photo = apps.get_model("photos", "Photo")
    FixedPriceITem = apps.get_model("items", "FixedPriceItem")

    content_type = ContentType.objects.get_for_model(FixedPriceITem)

    for photo in Photo.objects.all():
        if photo.item:
            user_id = photo.item.user_id

            new_photo = TempPhoto(
                file=photo.file,
                item_uuid=item_uuid,
                content_type_id=content_type.id,
                object_id=FixedPriceITem.objects.get(
                    user_id=user_id, temp_item_id=photo.item.id
                ).item_uuid,
            )
            new_photo.save()


class Migration(migrations.Migration):
    dependencies = [
        ("photos", "0002_tempphoto"),
    ]

    operations = [
        migrations.RunPython(migrate_photo_data),
    ]
