# Generated by Django 4.2.4 on 2023-08-28 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("photos", "0004_delete_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tempphoto",
            name="content_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="photos",
                to="contenttypes.contenttype",
            ),
        ),
    ]
