# Generated by Django 4.2.4 on 2023-08-29 02:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("photos", "0005_alter_tempphoto_content_type"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TempPhoto",
            new_name="Photo",
        ),
    ]
