# Generated by Django 4.2.1 on 2023-05-25 04:04

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user_ID", models.PositiveBigIntegerField()),
                ("is_negotiable", models.BooleanField(default=False)),
                ("is_sold", models.BooleanField(default=False)),
                ("price", models.PositiveIntegerField()),
                (
                    "used_years",
                    models.CharField(
                        choices=[
                            ("under 1 yr", "1년 이하"),
                            ("between 1 and 2 yr", "1년~2년"),
                            ("between 2 and 3 yr", "2년~3년"),
                            ("between 3 and 4 yr", "3년~4년"),
                            ("between 4 and 5 yr", "4년~5년"),
                            ("over 5 yr", "5년 이상"),
                        ],
                        max_length=20,
                    ),
                ),
                ("manufactured_date", models.DateField(blank=True, null=True)),
                ("warranty_date", models.DateField(blank=True, null=True)),
                ("description", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("refrigerator", "냉장고"),
                            ("dish washer", "식기세척기"),
                            ("showcase", "쇼케이스"),
                            ("sink", "싱크대"),
                            ("gas range", "화구/가스레인지"),
                            ("kiosk", "포스기계/키오스크"),
                            ("talbe", "테이블"),
                            ("packaging machine", "포장기계"),
                            ("air conditioner", "에어컨"),
                            ("extra", "기타"),
                        ],
                        max_length=25,
                    ),
                ),
                ("dday_date", models.DateField(blank=True, null=True)),
                ("location", models.TextField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
