# Generated by Django 4.2.4 on 2023-08-30 08:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="auctionitem",
            name="is_over",
            field=models.BooleanField(default=False),
        ),
    ]
