# Generated by Django 4.2.6 on 2023-11-10 04:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="auctionitem",
            name="used_period",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="fixedpriceitem",
            name="used_period",
            field=models.IntegerField(default=0),
        ),
    ]
