# Generated by Django 4.2.1 on 2023-05-25 07:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="is_liked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="item",
            name="item_name",
            field=models.CharField(default="", max_length=20),
        ),
    ]
