# Generated by Django 4.2.4 on 2023-09-05 02:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0002_auctionitem_is_over"),
    ]

    operations = [
        migrations.RenameField(
            model_name="auctionitem",
            old_name="is_over",
            new_name="is_overdue",
        ),
        migrations.AddField(
            model_name="auctionitem",
            name="is_bidded",
            field=models.BooleanField(default=False),
        ),
    ]
