# Generated by Django 4.2.6 on 2023-11-10 05:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0002_auctionitem_used_period_fixedpriceitem_used_period"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="auctionitem",
            name="used_period",
        ),
        migrations.RemoveField(
            model_name="fixedpriceitem",
            name="used_period",
        ),
    ]
