# Generated by Django 4.2.1 on 2023-05-25 10:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0003_rename_user_id_item_user_id_remove_item_location_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="category",
            field=models.CharField(
                choices=[
                    ("냉장고", "Refrigerator"),
                    ("식기세척기", "Dishwasher"),
                    ("쇼케이스", "Showcase"),
                    ("싱크대", "Sink"),
                    ("화구/가스레인지", "Gasrange"),
                    ("포스기계/키오스크", "Kiosk"),
                    ("테이블", "Table"),
                    ("포장기계", "Packing"),
                    ("에어컨", "Aircon"),
                    ("기타", "Extra"),
                ],
                max_length=25,
            ),
        ),
    ]
