# Generated by Django 4.2.1 on 2023-05-25 11:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0004_alter_item_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="category",
            field=models.CharField(
                choices=[
                    ("냉장고", "냉장고"),
                    ("식기세척기", "식기세척기"),
                    ("쇼케이스", "쇼케이스"),
                    ("싱크대", "싱크대"),
                    ("화구/가스레인지", "화구/가스레인지"),
                    ("포스기계/키오스크", "포스기계/키오스크"),
                    ("테이블", "테이블"),
                    ("포장기계", "포장기계"),
                    ("에어컨", "에어컨"),
                    ("기타", "기타"),
                ],
                max_length=25,
            ),
        ),
    ]
