# Generated by Django 4.2.4 on 2023-09-06 01:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0004_auctionitem_successful_bid_price"),
    ]

    operations = [
        migrations.RenameField(
            model_name="auctionitem",
            old_name="successful_bid_price",
            new_name="winning_bid",
        ),
    ]
