# Generated by Django 4.2.5 on 2023-09-14 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_customuser_delete_user"),
        ("items", "0005_rename_successful_bid_price_auctionitem_winning_bid"),
    ]

    operations = [
        migrations.AddField(
            model_name="auctionitem",
            name="temp_buy_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_purchased_items",
                to="users.customuser",
            ),
        ),
        migrations.AddField(
            model_name="auctionitem",
            name="temp_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_uploaded_items",
                to="users.customuser",
            ),
        ),
        migrations.AddField(
            model_name="fixedpriceitem",
            name="temp_buy_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_purchased_items",
                to="users.customuser",
            ),
        ),
        migrations.AddField(
            model_name="fixedpriceitem",
            name="temp_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_uploaded_items",
                to="users.customuser",
            ),
        ),
    ]
