# Generated by Django 4.2.1 on 2023-05-25 11:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0005_alter_item_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="location",
            field=models.CharField(
                choices=[
                    ("강남구", "강남구"),
                    ("강동구", "강동구"),
                    ("강북구", "강북구"),
                    ("강서구", "강서구"),
                    ("관악구", "관악구"),
                    ("광진구", "광진구"),
                    ("구로구", "구로구"),
                    ("금천구", "금천구"),
                    ("노원구", "노원구"),
                    ("도봉구", "도봉구"),
                    ("동대문구", "동대문구"),
                    ("동작구", "동작구"),
                    ("마포구", "마포구"),
                    ("서대문구", "서대문구"),
                    ("서초구", "서초구"),
                    ("성동구", "성동구"),
                    ("성북구", "성북구"),
                    ("송파구", "송파구"),
                    ("양천구", "양천구"),
                    ("영등포구", "영등포구"),
                    ("용산구", "용산구"),
                    ("은평구", "은평구"),
                    ("종로구", "종로구"),
                    ("중구", "중구"),
                    ("중량구", "중량구"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="used_years",
            field=models.CharField(
                choices=[
                    ("1년 이하", "1년 이하"),
                    ("1년~2년", "1년~2년"),
                    ("2년~3년", "2년~3년"),
                    ("3년~4년", "3년~4년"),
                    ("4년~5년", "4년~5년"),
                    ("5년 이상", "5년 이상"),
                ],
                max_length=20,
            ),
        ),
    ]
