# Generated by Django 4.2.5 on 2023-09-15 01:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0006_auctionitem_temp_buy_user_auctionitem_temp_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="auctionitem",
            name="buy_user_id",
        ),
        migrations.RemoveField(
            model_name="auctionitem",
            name="user_id",
        ),
        migrations.RemoveField(
            model_name="fixedpriceitem",
            name="buy_user_id",
        ),
        migrations.RemoveField(
            model_name="fixedpriceitem",
            name="user_id",
        ),
    ]
