# Generated by Django 4.2.6 on 2023-11-11 01:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0006_alter_auctionitem_used_years_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auctionitem",
            name="manufactured_date",
            field=models.DateField(blank=True, default="2023-01-01", null=True),
        ),
        migrations.AlterField(
            model_name="auctionitem",
            name="used_years",
            field=models.CharField(
                choices=[
                    ("1년 이하", "1년 이하"),
                    ("1년~2년", "1년~2년"),
                    ("2년~3년", "2년~3년"),
                    ("3년~4년", "3년~4년"),
                    ("4년~5년", "4년~5년"),
                    ("5년 이상", "5년 이상"),
                ],
                default="1년 이하",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="fixedpriceitem",
            name="manufactured_date",
            field=models.DateField(blank=True, default="2023-01-01", null=True),
        ),
        migrations.AlterField(
            model_name="fixedpriceitem",
            name="used_years",
            field=models.CharField(
                choices=[
                    ("1년 이하", "1년 이하"),
                    ("1년~2년", "1년~2년"),
                    ("2년~3년", "2년~3년"),
                    ("3년~4년", "3년~4년"),
                    ("4년~5년", "4년~5년"),
                    ("5년 이상", "5년 이상"),
                ],
                default="1년 이하",
                max_length=20,
            ),
        ),
    ]
