# Generated by Django 4.2.1 on 2023-05-29 10:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0006_item_location_alter_item_used_years"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="user_id",
            field=models.TextField(default=""),
        ),
    ]
