# Generated by Django 4.2.5 on 2023-09-15 02:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0007_remove_auctionitem_buy_user_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="auctionitem",
            old_name="temp_buy_user",
            new_name="buy_user",
        ),
        migrations.RenameField(
            model_name="auctionitem",
            old_name="temp_user",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="fixedpriceitem",
            old_name="temp_buy_user",
            new_name="buy_user",
        ),
        migrations.RenameField(
            model_name="fixedpriceitem",
            old_name="temp_user",
            new_name="user",
        ),
    ]
