# Generated by Django 4.2.1 on 2023-05-30 04:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0007_alter_item_user_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="is_liked",
        ),
    ]
