# Generated by Django 4.2.6 on 2023-11-11 04:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0007_alter_auctionitem_manufactured_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="auctionitem",
            name="is_manufactured",
        ),
        migrations.RemoveField(
            model_name="auctionitem",
            name="manufactured_date",
        ),
        migrations.RemoveField(
            model_name="auctionitem",
            name="used_years",
        ),
        migrations.RemoveField(
            model_name="fixedpriceitem",
            name="is_manufactured",
        ),
        migrations.RemoveField(
            model_name="fixedpriceitem",
            name="is_negotiable",
        ),
        migrations.RemoveField(
            model_name="fixedpriceitem",
            name="manufactured_date",
        ),
        migrations.RemoveField(
            model_name="fixedpriceitem",
            name="used_years",
        ),
    ]
