# Generated by Django 4.2.5 on 2023-09-15 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_remove_customuser_temp_user_id"),
        ("items", "0008_rename_temp_buy_user_auctionitem_buy_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auctionitem",
            name="user",
            field=models.ForeignKey(
                default="2009fe2b-9d93-4bd8-a773-0a25d4be5b0f",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_uploaded_items",
                to="users.customuser",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="fixedpriceitem",
            name="user",
            field=models.ForeignKey(
                default="2009fe2b-9d93-4bd8-a773-0a25d4be5b0f",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_uploaded_items",
                to="users.customuser",
            ),
            preserve_default=False,
        ),
    ]
