# Generated by Django 4.2.1 on 2023-05-31 04:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0008_remove_item_is_liked"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
