# Generated by Django 4.2.5 on 2023-11-07 05:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0009_alter_auctionitem_user_alter_fixedpriceitem_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="auctionitem",
            name="used_period",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="fixedpriceitem",
            name="used_period",
            field=models.IntegerField(default=0),
        ),
    ]
