# Generated by Django 4.2.1 on 2023-05-31 04:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0009_item_is_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="buy_user_id",
            field=models.TextField(default=""),
        ),
    ]
