# Generated by Django 4.2.1 on 2023-07-25 07:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0012_alter_item_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="category",
            field=models.CharField(
                choices=[
                    ("가구", "가구"),
                    ("커피머신", "커피머신"),
                    ("제빙기", "제빙기"),
                    ("냉장고/냉동고", "냉장고/냉동고"),
                    ("세척기", "세척기"),
                    ("쇼케이스", "쇼케이스"),
                    ("싱크대/작업대", "싱크대/작업대"),
                    ("가스레인지/인덕션", "가스레인지/인덕션"),
                    ("포장기계", "포장기계"),
                    ("에어컨", "에어컨"),
                    ("기타", "기타"),
                ],
                max_length=25,
            ),
        ),
    ]
