# Generated by Django 4.2.2 on 2023-07-26 08:59

from django.db import migrations, models


def update_category_values(apps, schema_editor):
    Item = apps.get_model("items", "Item")

    # Add the logic for updating the existing data according to your requirements
    kiosk_items = Item.objects.filter(category="포스기계/키오스크")
    table_items = Item.objects.filter(category="테이블")

    for item in kiosk_items.union(table_items):
        item.category = "기타"
        item.save()

    # ("냉장고", "냉장고") -> ("냉장고/냉동고", "냉장고/냉동고")
    refrigerator_items = Item.objects.filter(category="냉장고")
    for item in refrigerator_items:
        item.category = "냉장고/냉동고"
        item.save()

    # ("식기세척기", "식기세척기") -> ("세척기", "세척기")
    dishwasher_items = Item.objects.filter(category="식기세척기")
    for item in dishwasher_items:
        item.category = "세척기"
        item.save()

    # ("싱크대", "싱크대") -> ("싱크대/작업대", "싱크대/작업대")
    sink_items = Item.objects.filter(category="싱크대")
    for item in sink_items:
        item.category = "싱크대/작업대"
        item.save()

    # ("화구/가스레인지", "화구/가스레인지") -> ("가스레인지/인덕션", "가스레인지/인덕션")
    gasrange_items = Item.objects.filter(category="화구/가스레인지")
    for items in gasrange_items:
        item.category = "가스레인지/인덕션"
        item.save()


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0012_alter_item_dday_date_alter_item_manufactured_date_and_more"),
    ]

    operations = [
        migrations.RunPython(update_category_values),
        migrations.AlterField(
            model_name="item",
            name="category",
            field=models.CharField(
                choices=[
                    ("가구", "가구"),
                    ("커피머신", "커피머신"),
                    ("제빙기", "제빙기"),
                    ("냉장고/냉동고", "냉장고/냉동고"),
                    ("세척기", "세척기"),
                    ("쇼케이스", "쇼케이스"),
                    ("싱크대/작업대", "싱크대/작업대"),
                    ("가스레인지/인덕션", "가스레인지/인덕션"),
                    ("포장기계", "포장기계"),
                    ("에어컨", "에어컨"),
                    ("기타", "기타"),
                ],
                max_length=25,
            ),
        ),
    ]
