# Generated by Django 4.2.4 on 2023-08-28 06:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0013_auctionitem_fixedpriceitem"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Item",
        ),
    ]
