# Generated by Django 4.2.1 on 2023-08-03 06:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0013_alter_item_category"),
        ("items", "0014_alter_item_dday_date_alter_item_warranty_date"),
    ]

    operations = []
