# Generated by Django 4.2.4 on 2023-08-29 04:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0014_delete_item"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auctionitem",
            name="deadline",
            field=models.DateField(),
        ),
    ]
