# Generated by Django 4.2.4 on 2023-08-29 04:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0015_alter_auctionitem_deadline"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="auctionitem",
            name="temp_item_id",
        ),
        migrations.RemoveField(
            model_name="auctionitem",
            name="temp_user_id",
        ),
        migrations.RemoveField(
            model_name="fixedpriceitem",
            name="temp_item_id",
        ),
        migrations.RemoveField(
            model_name="fixedpriceitem",
            name="temp_user_id",
        ),
    ]
