# Generated by Django 4.2.1 on 2023-08-10 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0014_alter_customuser_nick_name"),
        ("items", "0016_rename_buy_user_id_item_buy_user_uuid_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="user_uuid",
        ),
        migrations.AddField(
            model_name="item",
            name="buy_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="purchased_items",
                to="users.customuser",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="user",
            field=models.ForeignKey(
                default="56a64b38-7036-4cf7-a00b-95e7e3b8cc3e",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="uploaded_items",
                to="users.customuser",
            ),
            preserve_default=False,
        ),
    ]
