# Generated by Django 4.2.1 on 2023-08-16 01:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0017_remove_item_buy_user_uuid_remove_item_user_uuid_and_more"),
    ]

    operations = []
