# Generated by Django 4.2.1 on 2023-08-16 02:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0018_remove_item_buy_user_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="buy_user_uuid",
            field=models.TextField(default=""),
        ),
    ]
