# Generated by Django 4.2.1 on 2023-08-16 06:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0019_alter_item_buy_user_uuid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="buy_user_uuid",
        ),
    ]
