# Generated by Django 4.2.1 on 2023-05-29 11:26

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("items", "0007_alter_item_user_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Wishlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user_id", models.TextField()),
                ("name", models.CharField(max_length=150)),
                (
                    "item",
                    models.ManyToManyField(related_name="wishlists", to="items.item"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
