# Generated by Django 4.2.4 on 2023-08-30 07:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("items", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Wishlist",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "wishlist_uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("user_id", models.TextField()),
                ("name", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "auction_items",
                    models.ManyToManyField(
                        related_name="wishlists", to="items.auctionitem"
                    ),
                ),
                (
                    "fixed_price_items",
                    models.ManyToManyField(
                        related_name="wishlists", to="items.fixedpriceitem"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
