# Generated by Django 4.2.6 on 2023-10-25 06:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0001_initial"),
        ("wishlists", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wishlist",
            name="auction_items",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="wishlists", to="items.auctionitem"
            ),
        ),
        migrations.AlterField(
            model_name="wishlist",
            name="fixed_price_items",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="wishlists",
                to="items.fixedpriceitem",
            ),
        ),
    ]
