# Generated by Django 4.2.5 on 2023-09-14 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_customuser_delete_user"),
        ("items", "0006_auctionitem_temp_buy_user_auctionitem_temp_user_and_more"),
        ("wishlists", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="wishlist",
            name="temp_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wishlists",
                to="users.customuser",
            ),
        ),
        migrations.CreateModel(
            name="WishlistFixedPriceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="items.fixedpriceitem",
                    ),
                ),
                (
                    "wishlist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wishlists.wishlist",
                    ),
                ),
            ],
            options={
                "unique_together": {("wishlist", "item")},
            },
        ),
        migrations.CreateModel(
            name="WishlistAuctionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="items.auctionitem",
                    ),
                ),
                (
                    "wishlist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wishlists.wishlist",
                    ),
                ),
            ],
            options={
                "unique_together": {("wishlist", "item")},
            },
        ),
    ]
