# Generated by Django 4.2.1 on 2023-05-29 11:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wishlists", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wishlist",
            name="name",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
