# Generated by Django 4.2.4 on 2023-08-24 03:06

from django.db import migrations
from django.contrib.contenttypes.models import ContentType


def migrate_wishlist_data(apps, schema_editor):
    TempWishlist = apps.get_model("wishlists", "TempWishlist")
    Wishlist = apps.get_model("wishlists", "Wishlist")
    WishlistItemRelation = apps.get_model("wishlists", "WishlistItemRelation")
    FixedPriceItem = apps.get_model("items", "FixedPriceItem")

    for wishlist in Wishlist.objects.all():
        new_wishlist = TempWishlist.objects.create(
            user_id=wishlist.user_id,
            name=wishlist.name,
        )

        fixed_price_items = FixedPriceItem.objects.filter(user_id=wishlist.user_id)

        for item in fixed_price_items:
            WishlistItemRelation.objects.create(
                wishlist=new_wishlist,
                content_type_id=ContentType.objects.get_for_model(FixedPriceItem).id,
                object_id=item.item_uuid,
            )


class Migration(migrations.Migration):
    dependencies = [
        ("wishlists", "0002_tempwishlist_wishlistitemrelation"),
    ]

    operations = [
        migrations.RunPython(migrate_wishlist_data),
    ]
