# Generated by Django 4.2.1 on 2023-05-29 11:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wishlists", "0002_alter_wishlist_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="wishlist",
            old_name="item",
            new_name="items",
        ),
    ]
