# Generated by Django 4.2.1 on 2023-08-16 01:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wishlists", "0002_rename_user_id_wishlist_user_id_firebase_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wishlist",
            name="user_id_firebase",
        ),
    ]
