# Generated by Django 4.2.1 on 2023-08-16 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0019_alter_item_buy_user_uuid"),
        ("users", "0014_alter_customuser_nick_name"),
        ("wishlists", "0003_remove_wishlist_user_id_firebase"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wishlist",
            name="items",
            field=models.ManyToManyField(
                null=True, related_name="wishlists", to="items.item"
            ),
        ),
        migrations.AlterField(
            model_name="wishlist",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wishlists",
                to="users.customuser",
            ),
        ),
    ]
