# Generated by Django 4.2.4 on 2023-08-28 06:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wishlists", "0003_auto_20230824_1206"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Wishlist",
        ),
    ]
