# Generated by Django 4.2.4 on 2023-08-28 08:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0014_delete_item"),
        ("wishlists", "0004_delete_wishlist"),
    ]

    operations = [
        migrations.AddField(
            model_name="tempwishlist",
            name="auction_items",
            field=models.ManyToManyField(
                related_name="wishlists", to="items.auctionitem"
            ),
        ),
        migrations.AddField(
            model_name="tempwishlist",
            name="items",
            field=models.ManyToManyField(
                related_name="wishlists", to="items.fixedpriceitem"
            ),
        ),
        migrations.DeleteModel(
            name="WishlistItemRelation",
        ),
    ]
