# Generated by Django 4.2.1 on 2023-08-16 06:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0019_alter_item_buy_user_uuid"),
        ("wishlists", "0004_alter_wishlist_items_alter_wishlist_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wishlist",
            name="items",
            field=models.ManyToManyField(related_name="wishlists", to="items.item"),
        ),
    ]
