# Generated by Django 4.2.4 on 2023-08-29 02:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0014_delete_item"),
        ("wishlists", "0005_tempwishlist_auction_items_tempwishlist_items_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TempWishlist",
            new_name="Wishlist",
        ),
    ]
