# Generated by Django 4.2.5 on 2023-11-07 03:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0009_alter_auctionitem_user_alter_fixedpriceitem_user"),
        ("wishlists", "0006_alter_wishlist_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wishlist",
            name="auction_items",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="wishlists", to="items.auctionitem"
            ),
        ),
        migrations.AlterField(
            model_name="wishlist",
            name="fixed_price_items",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="wishlists",
                to="items.fixedpriceitem",
            ),
        ),
    ]
