# Generated by Django 4.2.5 on 2023-10-06 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_customuser_blocked_users"),
        ("chats", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="chat_room",
        ),
        migrations.AddField(
            model_name="message",
            name="chat",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="messages",
                to="chats.chat",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="image",
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("image", "Image"),
                    ("auctionNotSell", "Auction Not Sell"),
                ],
                default="text",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="receiver_user_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recieved_messages",
                to="users.customuser",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="sender_user_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sent_messages",
                to="users.customuser",
            ),
        ),
    ]
