# Generated by Django 4.2.5 on 2023-10-06 01:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chats", "0002_remove_message_chat_room_message_chat_message_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chat",
            name="last_chat",
        ),
    ]
