# Generated by Django 4.2.5 on 2023-10-11 01:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chats", "0003_remove_chat_last_chat"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chat",
            name="last_chat_date",
        ),
        migrations.AddField(
            model_name="chat",
            name="buyer_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="chat",
            name="seller_active",
            field=models.BooleanField(default=False),
        ),
    ]
