from django.urls import path
from .views import (
    UserFixedPriceItemSellingList,
    UserAuctionItemSellingList,
    UserSoldList,
    BusinessLicense,
    UserFixedPriceItemPurchaseList,
    UserAuctionItemPurchaseList,
    UpdateFCMToken,
    UserCreate,
    UpdateNickname,
    CheckNickname,
    Logout,
    DeleteUser,
    UserInformation,
    MarketingInformation,
    UpdateProfile,
)

urlpatterns = [
    path("", UserCreate.as_view(), name="user_create"),
    path("solds", UserSoldList.as_view()),
    path("sells/auction", UserAuctionItemSellingList.as_view()),
    path("sells/fixed-price", UserFixedPriceItemSellingList.as_view()),
    path("business-license", BusinessLicense.as_view()),
    path("purchases/fixed-price", UserFixedPriceItemPurchaseList.as_view()),
    path("purchases/auction", UserAuctionItemPurchaseList.as_view()),
    path("fcm-token", UpdateFCMToken.as_view(), name="update_fcm_token"),
    path("nickname", UpdateNickname.as_view(), name="update_nickname"),
    path("check-nickname", CheckNickname.as_view(), name="check_nickcname"),
    path("logout", Logout.as_view(), name="logout"),
    path("deletion", DeleteUser.as_view(), name="delete_user"),
    path("informations", UserInformation.as_view(), name="informations"),
    path("marketing", MarketingInformation.as_view(), name="marketing"),
    path("profile", UpdateProfile.as_view(), name="profile"),
]
