from django.urls import path
from .views import (
    UserFixedPriceItemSellingList,
    UserAuctionItemSellingList,
    UserSoldList,
    BusinessLicense,
    UserFixedPriceItemPurchaseList,
    UserAuctionItemPurchaseList,
    UpdateFCMToken,
    UserCreate,
    UpdateNickname,
    CheckNickname,
    Logout,
    DeleteUser,
    UserInformation,
    MarketingInformation,
    UpdateProfile,
    PushNotification,
    BlockUser,
    UnBlockUser,
    BlockedUserList,
    CheckPhoneNumber,
    CheckKakaoID,
    UpdatePhoneNumber,
)

urlpatterns = [
    path("", UserCreate.as_view(), name="user_create"),
    path("solds", UserSoldList.as_view()),
    path("sells/auction", UserAuctionItemSellingList.as_view()),
    path("sells/fixed-price", UserFixedPriceItemSellingList.as_view()),
    path("business-license", BusinessLicense.as_view()),
    path("purchases/fixed-price", UserFixedPriceItemPurchaseList.as_view()),
    path("purchases/auction", UserAuctionItemPurchaseList.as_view()),
    path("fcm-token", UpdateFCMToken.as_view(), name="update_fcm_token"),
    path("nickname", UpdateNickname.as_view(), name="update_nickname"),
    path("check-phone-number", CheckPhoneNumber.as_view(), name="check_phone_number"),
    path("check-nickname", CheckNickname.as_view(), name="check_nickcname"),
    path("logout", Logout.as_view(), name="logout"),
    path("deletion", DeleteUser.as_view(), name="delete_user"),
    path("informations", UserInformation.as_view(), name="informations"),
    path("marketing", MarketingInformation.as_view(), name="marketing"),
    path("profile", UpdateProfile.as_view(), name="profile"),
    path("chat-notification", PushNotification.as_view(), name="chat_notification"),
    path("<uuid:pk>/block", BlockUser.as_view(), name="block_user"),
    path("<uuid:pk>/unblock", UnBlockUser.as_view(), name="unblock_user"),
    path("blocked", BlockedUserList.as_view(), name="blocked_user_list"),
    path("check-kakao-id", CheckKakaoID.as_view(), name="check_kakao_id"),
    path("phone-number", UpdatePhoneNumber.as_view(), name="update phone_number"),
]
