# Generated by Django 4.2.6 on 2023-10-25 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("biddings", "0001_initial"),
        ("items", "0001_initial"),
        ("users", "0007_customuser_blocked_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="bidding",
            name="auction_item",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="biddings",
                to="items.auctionitem",
            ),
        ),
        migrations.AddField(
            model_name="bidding",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="biddings",
                to="users.customuser",
            ),
        ),
    ]
