# Generated by Django 4.2.5 on 2023-09-14 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_customuser_delete_user"),
        ("biddings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bidding",
            name="temp_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="biddings",
                to="users.customuser",
            ),
        ),
    ]
