# Generated by Django 4.2.5 on 2023-09-15 01:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("biddings", "0002_bidding_temp_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bidding",
            name="user_id",
        ),
    ]
