# Generated by Django 4.2.5 on 2023-09-15 02:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("biddings", "0003_remove_bidding_user_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bidding",
            old_name="temp_user",
            new_name="user",
        ),
    ]
